app = "byob-video"
primary_region = "sjc"

[build]

[env]
  PHX_HOST = "byob.video"
  PHX_SERVER = "true"
  BYOB_DB_PATH = "/data/byob.db"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/"

[mounts]
  source = "byob_data"
  destination = "/data"
