defmodule ByobWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :byob

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_byob_key",
    signing_salt: "DkrNptIj",
    same_site: "Lax"
  ]

  socket "/extension", ByobWeb.ExtensionSocket, websocket: [check_origin: false]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :byob,
    gzip: not code_reloading?,
    only: ByobWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # Allow autoplay for YouTube embeds
  plug :permissions_policy

  defp permissions_policy(conn, _opts) do
    Plug.Conn.put_resp_header(conn, "permissions-policy", "autoplay=*, encrypted-media=*")
  end

  plug Plug.Session, @session_options
  plug ByobWeb.Router
end
